export type NpcId = "lin" | "yu" | "shen";
export type NpcProfile = {
  id: string;
  name: string;
  age: number;
  gender: string;
  orientation: string;
  role: string;
  background: string;
  personality: string;
  voice: string;
  friendship: string;
  romance: string;
  studyStyle: string;
  boundaries: string;
};
export type NpcMemory = { text: string; updatedAt: number };
export type ChatMessage = {
  id: string;
  npcId: NpcId;
  role: "user" | "assistant";
  text: string;
  createdAt: number;
  sessionId?: string;
  jobId?: string;
};
export type CourseBookmark = {
  id: string;
  title: string;
  subject: string;
  url: string;
  part: number;
  partTitle: string;
  partUrl: string;
  position: string;
  note: string;
  updatedAt: number;
};
export type StudySession = {
  id: string;
  npcId: NpcId;
  mode: "together" | "dual";
  scene: "静室" | "泉边" | "檐下";
  courseId: string;
  length: "short" | "standard" | "long";
  durationMs: number;
  elapsedMs: number;
  startedAt: number;
  deadline: number;
  status: "running" | "paused" | "ended";
  createdAt: number;
  endedAt: number;
  gameDay: number;
  ending: "none" | "waiting" | "generating" | "complete" | "failed";
  endingJobId: string;
  feedback: string;
  understanding: string;
};
export type StoryChapter = {
  id: string;
  sessionId: string;
  npcId: NpcId;
  mode: "together" | "dual";
  title: string;
  text: string;
  createdAt: number;
  minutes: number;
  favorite: boolean;
  readPosition: number;
};
export type Generation = {
  id: string;
  npcId: NpcId;
  kind: "chat" | "during" | "ending" | "test";
  sessionId: string;
  state: "pending" | "complete" | "failed" | "cancelled";
  error: string;
  partial: string;
  body: Record<string, unknown>;
  applied: boolean;
  uncertain?: boolean;
};
export type CompanionData = {
  pendingDeletes: string[];
  schema: 1;
  profileId: string;
  messages: ChatMessage[];
  memories: Record<NpcId, NpcMemory>;
  drafts: Record<string, string>;
  courses: CourseBookmark[];
  sessions: StudySession[];
  chapters: StoryChapter[];
  jobs: Generation[];
  lastCourseId: string;
};
